apps/courses/urls.py
# _*_coding:utf-8 _*_
from django.conf.urls import url, include

from courses.views import CoursesListView, CourseDetail, CourseInfoView, CommentsView, AddCommentsView, VideoPlayView

urlpatterns = [

    # 课程机构列表
    url(r'^list/$', CoursesListView.as_view(), name='course_list'),
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetail.as_view(), name='course_detail'),
    url(r'^info/(?P<course_id>\d+)/$', CourseInfoView.as_view(), name='course_info'),
    url(r'^comments/(?P<course_id>\d+)/$', CommentsView.as_view(), name='course_comments'),
    # 添加课程评论
    url(r'^add_comment/$', AddCommentsView.as_view(), name='add_comment'),
    url(r'video/(?P<video_id>\d+)/$', VideoPlayView.as_view(), name='video_play')
]

apps/organization/urls.py
# _*_ coding:utf-8 _*_ 

from django.conf.urls import url, include

from .views import OrgView, AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeachersView, AddFavView, \
    TeacherListView, TeacherDetailView

__author__ = 'gandazhi'
__date__ = '17-7-8 下午7:41'

urlpatterns = [

    # 课程机构列表
    url(r'^list/$', OrgView.as_view(), name='org_list'),
    # 我要学习的url
    url(r'^add_ask/$', AddUserAskView.as_view(), name='add_ask'),
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name='org_home'),
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name='org_course'),
    url(r'^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name='org_desc'),
    url(r'^org_teachers/(?P<org_id>\d+)/$', OrgTeachersView.as_view(), name='org_teachers'),
    # 收藏机构和取消收藏机构
    url(r'^add_fav/$', AddFavView.as_view(), name='add_fav'),
    # 讲师列表页
    url(r'^teacher/list/$', TeacherListView.as_view(), name='teacher_list'),
    # 讲师详情页
    url(r'^teachers/detail(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/users/urls.py
# _*_ coding:utf-8 _*_ 

from django.conf.urls import url, include

from users.views import UserInfoView, UploadImageView, UpdatePwdView, SendEmailCodeView, UpdateEmailView, MyCourseView, \
    MessageView, FavOrgView, FavCourseView, FavTeacherView

__author__ = 'gandazhi'
__date__ = '17-7-29 下午12:02'

urlpatterns = [
    url(r'^info/$', UserInfoView.as_view(), name='user_info'),
    url(r'^upload/image/$', UploadImageView.as_view(), name='upload_image'),
    url(r'^update/password/$', UpdatePwdView.as_view(), name='update_password'),
    url(r'^send_email_code/$', SendEmailCodeView.as_view(), name='send_email_code'),
    url(r'^update_email/$', UpdateEmailView.as_view(), name='update_email'),
    url(r'^my_course/$', MyCourseView.as_view(), name='my_course'),
    url(r'^message/$', MessageView.as_view(), name='message'),
    url(r'^myFav/org/$', FavOrgView.as_view(), name='myFav_org'),
    url(r'^myFav/course/$', FavCourseView.as_view(), name='myFav_course'),
    url(r'^myFav/teacher/$', FavTeacherView.as_view(), name='myFav_teacher'),
]

mx_online/urls.py
# _*_ coding:utf-8 _*_
"""mx_online URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.views.static import serve
import xadmin

from users.views import LoginView, RegisterView, ActiveUserView, ForgetPwdView, ResetPwdView, ModifyPwdView, LogoutView, \
    IndexView
from organization.views import OrgView
from mx_online.settings import MEDIA_ROOT, STATIC_ROOT

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url('^$', IndexView.as_view(), name='index'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)', ActiveUserView.as_view(), name='user_active'),
    url(r'^forget/$', ForgetPwdView.as_view(), name='forget_pwd'),
    url(r'^reset/(?P<reset_code>.*)', ResetPwdView.as_view(), name='reset_pwd'),
    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name='modify_pwd'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    # 课程机构页url配置
    url(r'^org/', include('organization.urls', namespace='org')),
    # 课程相关url配置
    url(r'^course/', include('courses.urls', namespace="course")),
    # 配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
    # 配置用户相关的url
    url(r'^users/', include('users.urls', namespace='users')),

]

handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

apps/courses/models.py
# _*_ coding:utf-8 _*_
from __future__ import unicode_literals
from datetime import datetime

from django.db import models

from organization.models import CourseOrg, Teacher


# Create your models here.


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name=u'所属机构', null=True, blank=True)
    name = models.CharField(max_length=50, verbose_name=u'课程名')
    desc = models.CharField(max_length=300, verbose_name=u'课程描述')
    detail = models.TextField(verbose_name=u'课程详情')
    degree = models.CharField(choices=(('primary', u'初级'), ('middle', u'中级'), ('high', u'高级')), verbose_name=u'课程难度'
                              , max_length=7)
    teacher = models.ForeignKey(Teacher, verbose_name=u'讲师', null=True, blank=True)
    learn_time = models.IntegerField(default=0, verbose_name=u'学习时长（分钟数）')
    students = models.IntegerField(default=0, verbose_name=u'学习人数')
    fav_num = models.IntegerField(default=0, verbose_name=u'收藏人数')
    image = models.ImageField(upload_to='courses/%Y/%m', verbose_name=u'封面图', max_length=100)
    click_num = models.IntegerField(default=0, verbose_name=u'点击数')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')
    category = models.CharField(max_length=20, verbose_name=u'课程类别', default=u'后端开发')
    tag = models.CharField(max_length=10, verbose_name=u'课程标签', default=u'')
    you_need_know = models.CharField(max_length=300, verbose_name=u'课程须知', default='')
    teacher_tell = models.CharField(max_length=300, verbose_name=u'老师告诉你', default='')
    is_banner = models.BooleanField(default=False, verbose_name=u'是否banner')

    class Meta:
        verbose_name = u'课程'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return '{0}'.format(self.name)

    def get_learn_user(self):
        return self.usercourse_set.all()[:5]


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'课程')
    name = models.CharField(max_length=100, verbose_name=u'章节名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'章节'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

    def get_lesson_video(self):
        # 获取章节
        return self.video_set.all()


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name=u'章节')
    name = models.CharField(max_length=100, verbose_name=u'视频名')
    url = models.CharField(max_length=200, verbose_name=u'访问地址', default='')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')
    learn_time = models.IntegerField(default=0, verbose_name=u'学习时长（分钟数）')

    class Meta:
        verbose_name = u'视频'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'课程')
    name = models.CharField(max_length=100, verbose_name=u'名称 ')
    download = models.FileField(upload_to='course/resource/%Y/%m', verbose_name=u'资源文件', max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name

templates/index.html
{% extends 'base.html' %}

{% block title %}慕学在线网{% endblock %}

{% load staticfiles %}

{% block custom_bread %}
{% endblock %}

{% block content %}
    <!--banner start-->
    <div class="banner">
        <div class="wp">
            <div class="fl">
                <div class="imgslide">
                    <ul class="imgs">
                        {% for banner in all_banners %}
                            <li>
                                <a href="{{ banner.url }}">
                                    <img width="1200" height="478"
                                         src="{{ MEDIA_URL }}{{ banner.image }}"/>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>

        </div>


    </div>
    <!--banner end-->
    <!--feature start-->
    <section>
        <div class="wp">
            <ul class="feature">
                <li class="feature1">
                    <img class="pic" src="{% static 'images/feature1.png' %}"/>
                    <p class="center">专业权威</p>
                </li>
                <li class="feature2">
                    <img class="pic" src="{% static 'images/feature2.png' %}"/>
                    <p class="center">课程最新</p>
                </li>
                <li class="feature3">
                    <img class="pic" src="{% static 'images/feature3.png' %}"/>
                    <p class="center">名师授课</p>
                </li>
                <li class="feature4">
                    <img class="pic" src="{% static 'images/feature4.png' %}"/>
                    <p class="center">数据真实</p>
                </li>
            </ul>
        </div>
    </section>
    <!--feature end-->
    <!--module1 start-->
    <section>
        <div class="module">
            <div class="wp">
                <h1>公开课程</h1>
                <div class="module1 eachmod">
                    <div class="module1_1 left">
                        <img width="228" height="614" src="{% static 'images/module1_1.jpg' %}"/>
                        <p class="fisrt_word">名师授课<br/>专业权威</p>
                        <a class="more" href="{% url 'course:course_list' %}">查看更多课程 ></a>
                    </div>
                    <div class="right group_list">
                        <div class="module1_2 box">
                            <div class="imgslide2">
                                <ul class="imgs">
                                    {% for course_banner in banner_course %}
                                        <li>
                                            <a href="{% url 'course:course_detail' course_banner.id %}">
                                                <img width="470" height="300"
                                                     src="{{ MEDIA_URL }}{{ course_banner.image }}"/>
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="unslider-arrow2 prev"></div>
                            <div class="unslider-arrow2 next"></div>
                        </div>
                        {% for index_course in course %}
                            <div class="module1_{{ forloop.counter|add:2 }} box">
                                <a href="{% url 'course:course_detail' index_course.id %}">
                                    <img width="233" height="190" src="{{ MEDIA_URL }}{{ index_course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="course-detail.html">
                                        <h2 title="{{ index_course.name }}">{{ index_course.name }}</h2>
                                    </a>
                                    <span class="fl">难度：<i class="key">{{ index_course.get_degree_display }}</i></span>
                                    <span class="fr">学习人数：{{ index_course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl"
                                          title="{{ index_course.course_org.name }}">{{ index_course.course_org.name }}</span>
                                    <span class="star fr">{{ index_course.fav_num }}</span>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="module greybg">
            <div class="wp">
                <h1>课程机构</h1>
                <div class="module3 eachmod">
                    <div class="module3_1 left">
                        <img width="228" height="463" src="{% static 'images/module3_1.jpg' %}"/>
                        <p class="fisrt_word">名校来袭<br/>权威认证</p>
                        <a class="more" href="{% url 'org:org_list' %}">查看更多机构 ></a>
                    </div>
                    <div class="right">
                        <ul>

                            {% for org in course_orgs %}
                                <li {% if forloop.counter|divisibleby:5 %}class="five"{% endif %}>
                                    <a href="{% url 'org:org_home' org.id %}">
                                        <div class="company">
                                            <img width="184" height="100"
                                                 src="{{ MEDIA_URL }}{{ org.image }}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>{{ org.tag }}</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="{{ org.name }}">{{ org.name }}</span></p>
                                    </a>
                                </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

{% block custom_js %}
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}

templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}机构首页{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
        <div class="header2 header">

            <div class="top">
                <div class="wp">
                    <div class="fl">
                        <p>联系方式：<b>3333333333</b></p>
                    </div>
                    {% if request.user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ request.user.nick_name }}<img class="down fr"
                                                                     src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20"
                                         src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80"
                                             src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                                    <dd>
                                        <h2>{{ request.user.first_name }}</h2>
                                        <p>{{ request.user.last_name }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    {% endif %}
                    <a href="usercenter-message.html">
                        <div class="msg-num"><span id="MsgNum">{{ request.user.unread_nums }}</span></div>
                    </a>
                </div>
            </div>


            <div class="middle companyheader">
                <div class="wp">
                    <img class="fl" style="width: 112px;height: 103px"
                         src="{% static 'media/org/2016/11/imooc.png' %}"/>
                    <div class="head fl">
                        <h1>
                            慕课网
                            <img src="{% static 'images/authentication.png' %}"/>
                            <img src="{% static 'images/gold.png' %}"/>
                        </h1>
                        <p class="fl">
                            <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                            <span class="precision company-credit" data-star-scope="5.0"></span>
                            <span class="key">5.0</span>
                        </p>
                    </div>
                    <div class="btn fr collectionbtn  notlogin" id="fav_btn" data-favid="22" data-fav-type="1">
                        {% if has_fav %}
                            已收藏
                        {% else %}
                            收藏
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    </header>
</section>
<section>
    <div class="wp">
        <ul class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'org:org_list' %}">课程机构</a>></li>
            <li>{% block page_path %}机构首页{% endblock %}</li>
        </ul>
    </div>
</section>

<section>
    <div class="wp list personal_list comp">
        <div class="left">
            <ul>
                <li {% if request.path|slice:'9' == '/org/home' %}class="active2"{% endif %}><a
                        href="{% url 'org:org_home' course_org.id %}">机构首页</a></li>
                <li {% if request.path|slice:'11' == '/org/course' %}class="active2"{% endif %}><a
                        href="{% url 'org:org_course' course_org.id %}">机构课程</a></li>
                <li {% if request.path|slice:'9' == '/org/desc' %}class="active2"{% endif %}><a
                        href="{% url 'org:org_desc' course_org.id %}">机构介绍</a></li>
                <li {% if request.path|slice:'17' == '/org/org_teachers' %}class="active2"{% endif %}><a
                        href="{% url 'org:org_teachers' course_org.id %}">机构讲师</a></li>
            </ul>
        </div>
        {% block right_form %}
        {% endblock %}
    </div>
</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
</div>
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">
    //收藏分享
    //收藏分享
    function add_fav(current_elem, fav_id, fav_type) {
        $.ajax({
            cache: false,
            type: "POST",
            url: "{% url 'org:add_fav' %}",
            data: {'fav_id': fav_id, 'fav_type': fav_type},
            async: true,
            beforeSend: function (xhr, settings) {
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function (data) {
                if (data.status == 'fail') {
                    if (data.msg == '用户未登录') {
                        window.location.href = "{% url 'login' %}";
                    } else {
                        alert(data.msg)
                    }

                } else if (data.status == 'success') {
                    current_elem.text(data.msg)
                }
            },
        });
    }

    $('.collectionbtn').on('click', function () {
        add_fav($(this), {{ course_org.id }}, 2);
    });

    $(function () {
        var $precision = $('.precision'),
            score = $precision.attr('data-star-scope'),
            option = {
                half: true,
                path: '{% static "images/" %}',
                precision: true,
                size: 24,
                starOff: 'g_star.png',
                starOn: 'r_star.png',
                starHalf: 'h_star.png',
                hints: ['极差', '差', '一般', '好评', '非常满意'],
                noRatedMsg: '暂时还未获得评价！',
                readOnly: true,
                score: score
            };
        $precision.raty(option);

        $('.jsFavBtn').on('click', function () {
            var type = $(this).attr('data-fav-type');
            if (type == '1') {
                favPraise($(this), 'fav', 1, '收藏');

            } else if (type == '3') {
                favPraise($(this), 'fav', 3);

            } else if (type == '11') {
                favPraise($(this), 'pra', 1);

            } else if (type == '4') {
                favPraise($(this), 'fav', 4);

            }
        });
    })
</script>


<script type="text/javascript">
    $(function () {
        $('.recordbtn1').click(function () {
            $('.recordbox1').show();
        });
        $('.recordbtn2').click(function () {
            $('.recordbox2').show();
        });

        $('.imgslide').unslider({
            speed: 500,               //  The speed to animate each slide (in milliseconds)
            delay: 3000,              //  The delay between slide animations (in milliseconds)
            complete: function () {
            },  //  A function that gets called after every slide animation
            keys: true,               //  Enable keyboard (left, right) arrow shortcuts
            dots: true,               //  Display dot navigation
            fluid: false              //  Support responsive design. May break non-responsive designs
        });
        var unslider = $('.imgslide').unslider();
        $('.unslider-arrow').click(function () {
            var fn = this.className.split(' ')[1];
            unslider.data('unslider')[fn]();
        });
    });
</script>

</body>
{% block custom_js %}{% endblock %}
</html>

templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}

{% block title %}我的收藏{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>
        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li><a href="{% url 'users:myFav_org' %}">课程机构</a></li>
                    <li><a href="{% url 'users:myFav_teacher' %}">授课教师 </a></li>
                    <li class="active"><a href="{% url 'users:myFav_course' %}">公开课程</a></li>
                </ul>

            </div>
            <div class="companycenter">
                <div class="group_list brief">

                    {% for course in course_list %}

                        <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="course-detail.html"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_time }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>

                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/usercenter-fav-org.html
{% extends 'usercenter-base.html' %}

{% block title %}我的收藏{% endblock %}

{% load staticfiles %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>

        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li {% if request.path|slice:'16' == '/users/myFav/org' %}class="active"{% endif %}><a href="{% url 'users:myFav_org' %}">课程机构</a></li>
                    <li {% if request.path|slice:'20' == '/users/myFav/teacher' %}class="active"{% endif %}><a href="{% url 'users:myFav_teacher' %}">授课教师 </a></li>
                    <li {% if request.path|slice:'19' == '/users/myFav/course' %}class="active"{% endif %}><a href="{% url 'users:myFav_course' %}">公开课程</a></li>
                </ul>
            </div>
            <div class="messagelist">
                {% for org in org_list %}
                    <div class="messages butler_list company company-fav-box">
                    <dl class="des fr">
                        <dt>
                            <a href="{% url 'org:org_home' org.id %}">
                                <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                            </a>
                        </dt>
                        <dd>
                            <h1><a href="org-detail-homepage.html">{{ org.name }}</a></h1>
                            <div class="pic fl" style="width:auto;">

                                <img src="{% static 'images/authentication.png' %}"/>


                                <img src="{% static 'images/gold.png' %}"/>

                            </div>
                            <span class="c8 clear">{{ org.address }}</span>
                            <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                        </dd>
                    </dl>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

templates/usercenter-message.html
{% extends 'usercenter-base.html' %}

{% block title %}我的消息{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的消息</li>
            </ul>
        </div>
    </section>

{% endblock %}

{% block right_content %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的消息</h1>
            </div>

        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li class="active"><a href="/user/message/">个人消息</a></li>
                </ul>
            </div>

        {% for user_message in message.object_list %}
            <div class="messagelist">
                <div class="messages">
                    <div class="fr">
                        <div class="top"><span class="fl time">{{ user_message.add_time }}</span><span
                                class="fr btn foldbtn"></span></div>
                        <p>
                            {{ user_message.message }}
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}

            <div class="pageturn pagerright">
                <ul class="pagelist">
                    {% if message.has_previous %}
                        <li class="long"><a href="?{{ message.previous_page_number.querystring }}">上一页</a></li>
                    {% endif %}

                    {% for page in message.pages %}
                        {% if page %}
                            {% ifequal page message.number %}
                                <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                            {% else %}
                                <li><a href="?{{ page.querystring }}" class="active">{{ page }}</a></li>
                            {% endifequal %}
                        {% else %}
                            <li class="none"><a href="">...</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if message.has_next %}
                        <li class="long"><a href="?{{ message.next_page_number.querystring }}">下一页</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>

    </div>
{% endblock %}